### ISSUE TITLE
Can't dockerise my app

### ISSUE THREAD

**Issue by romakoch** [blitz-js/legacy-framework#8]
### What is the problem?

There is an error after trying to dockerize my app, using the official tutorial

### Paste all your error logs here:

```
 > [builder 9/9] RUN yarn build:
blitz-js/blitz#16 2.810 yarn run v1.22.17
blitz-js/blitz#16 2.916 $ blitz build
blitz-js/blitz#16 4.021 Loaded env from /app/.env.local
blitz-js/blitz#16 4.022 Loaded env from /app/.env
blitz-js/blitz#16 4.738 /app/node_modules/esbuild/lib/main.js:1209
blitz-js/blitz#16 4.738         return callback(new Error(error), null);
blitz-js/blitz#16 4.738                         ^
blitz-js/blitz#16 4.738
blitz-js/blitz#16 4.738 Error: The service was stopped
blitz-js/blitz#16 4.738     at /app/node_modules/esbuild/lib/main.js:1209:25
blitz-js/blitz#16 4.738     at /app/node_modules/esbuild/lib/main.js:606:9
blitz-js/blitz#16 4.738     at Socket.afterClose (/app/node_modules/esbuild/lib/main.js:584:7)
blitz-js/blitz#16 4.738     at Socket.emit (node:events:402:35)
blitz-js/blitz#16 4.738     at endReadableNT (node:internal/streams/readable:1343:12)
blitz-js/blitz#16 4.738     at processTicksAndRejections (node:internal/process/task_queues:83:21)
blitz-js/blitz#16 4.738
blitz-js/blitz#16 4.738 Node.js v17.3.1
blitz-js/blitz#16 4.760 error Command failed with exit code 1.
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by saamrezaei** [comment]
Any updates on this?
